// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrksQ3o11R60VuWDNSMmi92kSgKCphr-8',
    appId: '1:495443396349:web:45cbcb8989607d0003e094',
    messagingSenderId: '495443396349',
    projectId: 'rectanglo-50778401',
    authDomain: 'rectanglo-50778401.firebaseapp.com',
    databaseURL: 'https://rectanglo-50778401.firebaseio.com',
    storageBucket: 'rectanglo-50778401.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkI-gxfLHbyc8iMUxe0vZcbG-Jjecr3ME',
    appId: '1:495443396349:android:8f77beb624770a2d03e094',
    messagingSenderId: '495443396349',
    projectId: 'rectanglo-50778401',
    databaseURL: 'https://rectanglo-50778401.firebaseio.com',
    storageBucket: 'rectanglo-50778401.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh7Pl6wZI3b-mQ1v4_qG7FhSPEGAYn-KQ',
    appId: '1:495443396349:ios:a8323c2bff089d9203e094',
    messagingSenderId: '495443396349',
    projectId: 'rectanglo-50778401',
    databaseURL: 'https://rectanglo-50778401.firebaseio.com',
    storageBucket: 'rectanglo-50778401.appspot.com',
    androidClientId: '495443396349-235o95e8iograrlckm8j6qumvdprsgce.apps.googleusercontent.com',
    iosClientId: '495443396349-fq3jk9fq1t6nujve1qgipfgvjiqoqnhq.apps.googleusercontent.com',
    iosBundleId: 'dev.studiocloud.rectanglo',
  );
}
